"""Every headline number for the pitch and the in-app Pitch mode, read from the measured files in deck/data, each
with its source path and key. Never type a number into a slide or the app: read it from deck/data/pitch-numbers.json.

    python -m mouna_harness pitch   # writes deck/data/pitch-numbers.json; claims whose source is missing are skipped
"""

from __future__ import annotations

import json
from pathlib import Path

DATA = Path(__file__).resolve().parents[2] / "deck" / "data"

# (id, claim with {} for the value, file, key path, format)
CLAIMS = [
    ("kannada_top1_3shot", "Lips learned from 3 examples per phrase: {} top-1 (Kannada dataset, 7 speakers, voiced)", "kannada-plana.json", "pooled.same_session.top1", "pct"),
    ("kannada_top3_3shot", "The right phrase is in the top three {} of the time", "kannada-plana.json", "pooled.same_session.top3", "pct"),
    ("encoder_npu_ms_sm8850", "Whole lip encoder on the Snapdragon 8 Elite Gen 5 NPU (iQOO 15's chip): {} per 1.92 s of lips", "device-report.json", "runs.static_npu.median_ms", "ms"),
    ("encoder_npu_ms_sm8850_app", "In the app's runtime (ONNX Runtime QNN, fp16) on the iQOO 15's chip: {} per window, every layer on the NPU", "device-litert.json", "devices.sm8850.runs.qnn_ctx_fp16.median_ms", "ms"),
    ("encoder_npu_ms_sm8650_app", "...and {} on the OnePlus 13R's chip (SM8650)", "device-litert.json", "devices.sm8650.runs.qnn_ctx_fp16.median_ms", "ms"),
    ("encoder_parity_phone", "Phone NPU vs laptop: embeddings agree to cosine {}", "device-litert.json", "devices.sm8850.runs.qnn_ctx_fp16.parity_cosine_vs_onnx_fp32", "cos"),
    ("encoder_int8_mb", "Encoder in int8: {} with no accuracy loss", "encoder-static.json", "int8.mb", "mb"),
    ("speak_direct_core", "Taught words spoken directly: {} (new core, held out by speaker)", "finale-core.json", "E17_speak_rule.core_5_negatives.taught_spoken_right", "pct"),
    ("speak_direct_before", "...against {} for the old head at the same false-speak rate", "finale-core.json", "E17_speak_rule.baseline_at_operating_point.taught_spoken_right", "pct"),
    ("speak_precision_core", "When Mouna speaks, it is right {} of the time", "finale-core.json", "E17_speak_rule.core_5_negatives.spoke_precision", "pct"),
    ("untaught_spoken_core", "Words it was never taught, spoken by mistake: {} (both old and new held near the 5% operating point)", "finale-core.json", "E17_speak_rule.core_5_negatives.untaught_spoken", "pct"),
    ("none_of_these_spoken", "Words the person once marked 'none of these': spoken by mistake {}", "finale-core.json", "E17_speak_rule.core_5_negatives.negative_word_spoken", "pct"),
    ("set_coverage", "When unsure, the right answer is in Mouna's shortlist {} of the time (target 90%)", "finale-core.json", "E16_prediction_set.held_out_coverage_mean", "pct"),
    ("truth_on_screen", "When Mouna does not speak, the right answer is on screen {} of the time", "finale-core.json", "E19_fallback_for_unspoken_taught_words.truth_shown_overall", "pct"),
    ("rescue_two_pictures", "Two pictures, left or right: the right one is there {} of the time", "finale-core.json", "E19_fallback_for_unspoken_taught_words.rescue_two.truth_shown", "pct"),
    ("aug_gain_3shot", "Teaching with mirrored and shifted copies: {} top-1 points", "kannada-augment.json", "3_shot.all_four.top1_gain_points", "pts"),
    ("half_face_top1", "Half a face, mirrored: {} top-1 (full face in the next line)", "kannada-halfface.json", "image_left_half.top1", "pct"),
    ("silent_same_session", "Our own silent recordings, same session: {} top-1", "finale-silent.json", "pooled.same_session.top1", "pct"),
    ("silent_next_session", "Next morning, no re-teaching: {} top-1", "finale-silent.json", "pooled.next_session.top1", "pct"),
    ("silent_untaught_spoken", "Silent untaught words spoken by mistake: {}", "finale-silent.json", "pooled.untaught.core_spoke", "pct"),
]


def _get(doc, path: str):
    for k in path.split("."):
        if not isinstance(doc, dict) or k not in doc:
            return None
        doc = doc[k]
    return doc


def _fmt(v: float, kind: str) -> str:
    return {"pct": f"{100 * v:.1f}%", "ms": f"{v:.1f} ms", "mb": f"{v:.0f} MB", "pts": f"{v:+.1f}", "cos": f"{v:.4f}"}[kind]


def build() -> dict:
    out = []
    for cid, text, file, key, kind in CLAIMS:
        f = DATA / file
        if not f.exists():
            continue
        v = _get(json.loads(f.read_text(encoding="utf-8")), key)
        if isinstance(v, (int, float)):
            out.append({"id": cid, "text": text.format(_fmt(v, kind)), "value": v, "source": f"deck/data/{file}", "key": key})
    return {"note": "generated by python -m mouna_harness pitch; do not edit by hand", "claims": out}


def write() -> Path:
    p = DATA / "pitch-numbers.json"
    p.write_text(json.dumps(build(), indent=2, ensure_ascii=False), encoding="utf-8")
    return p
